name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # toutes les 10 minutes
  workflow_dispatch:        # permet de le lancer à la main

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          echo "Pinging https://planning-poker-2kz1.onrender.com"
          # -L : suit les redirections
          # || true : ne jamais faire échouer le job, même si le curl échoue
          curl -L -s -o /dev/null https://planning-poker-2kz1.onrender.com || true
